modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "mccivilizations"
version = "${file.jarVersion}"
displayName = "MCCivilizations"
description = '''

'''

[[dependencies.mccivilizations]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mccivilizations]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mccivilizations]]
modId = "journeymap"
mandatory = false
versionRange = "[5.9.0,)"
ordering = "AFTER"
side = "CLIENT"
